### ISSUE TITLE
Can't get MMM-YrNow to work on fresh install

### ISSUE THREAD

**Issue by looolz** [YR/MMM-YrNow#24]
**Here is the output I get, maybe someone smarter than me can spot what's going on:**

> > magicmirror@2.22.0 start
> > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
> 
> [22.01.2023 20:48.18.855] [LOG]   Starting MagicMirror: v2.22.0
> [22.01.2023 20:48.18.861] [LOG]   Loading config ...
> [22.01.2023 20:48.18.871] [LOG]   Loading module helpers ...
> [22.01.2023 20:48.19.272] [LOG]   Initializing new module helper ...
> [22.01.2023 20:48.19.274] [LOG]   Module helper loaded: MMM-BackgroundSlideshow
> [22.01.2023 20:48.19.303] [LOG]   Initializing new module helper ...
> [22.01.2023 20:48.19.304] [LOG]   Module helper loaded: MMM-Entur-tavle
> [22.01.2023 20:48.19.307] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
> Require stack:
> - /home/pi/MagicMirror/modules/MMM-YrNow/node_helper.js
> - /home/pi/MagicMirror/js/app.js
> - /home/pi/MagicMirror/js/electron.js
> - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
> - 
> [22.01.2023 20:48.19.307] [LOG]   Loading module helpers ...
> [22.01.2023 20:48.19.308] [LOG]   Initializing new module helper ...
> [22.01.2023 20:48.19.309] [LOG]   Module helper loaded: MMM-BackgroundSlideshow
> [22.01.2023 20:48.19.310] [LOG]   Initializing new module helper ...
> [22.01.2023 20:48.19.310] [LOG]   Module helper loaded: MMM-Entur-tavle
> [22.01.2023 20:48.19.313] [ERROR] App threw an error during load
> [22.01.2023 20:48.19.314] [ERROR] Error: Cannot find module 'request'
> Require stack:
> - /home/pi/MagicMirror/modules/MMM-YrNow/node_helper.js
> - /home/pi/MagicMirror/js/app.js
> - /home/pi/MagicMirror/js/electron.js
> - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
> - 
>     at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
>     at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
>     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
>     at Module._load (node:internal/modules/cjs/loader:811:27)
>     at f._load (node:electron/js2c/asar_bundle:2:13328)
>     at Module.require (node:internal/modules/cjs/loader:1035:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-YrNow/node_helper.js:2:15)
>     at Module._compile (node:internal/modules/cjs/loader:1141:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
> [22.01.2023 20:48.19.316] [ERROR] Whoops! There was an uncaught exception...
> [22.01.2023 20:48.19.322] [ERROR] Error: Cannot find module 'request'
> Require stack:
> - /home/pi/MagicMirror/modules/MMM-YrNow/node_helper.js
> - /home/pi/MagicMirror/js/app.js
> - /home/pi/MagicMirror/js/electron.js
> - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
> - 
>     at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
>     at n._resolveFilename (node:electron/js2c/browser_init:2:109416)
>     at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
>     at Module._load (node:internal/modules/cjs/loader:811:27)
>     at f._load (node:electron/js2c/asar_bundle:2:13328)
>     at Module.require (node:internal/modules/cjs/loader:1035:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-YrNow/node_helper.js:2:15)
>     at Module._compile (node:internal/modules/cjs/loader:1141:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1196:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/pi/MagicMirror/modules/MMM-YrNow/node_helper.js',
>     '/home/pi/MagicMirror/js/app.js',
>     '/home/pi/MagicMirror/js/electron.js',
>     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
>     undefined
>   ]
> }
> [22.01.2023 20:48.19.322] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [22.01.2023 20:48.19.323] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> Fontconfig warning: ignoring UTF-8: not a valid region tag
> [22.01.2023 20:48.19.582] [LOG]   Launching application.
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
> failed to load driver: kms_swrast
> MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
> failed to load swrast driver
> ^X^C/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
>

**Comment by looolz** [comment]
> [22.01.2023 20:48.19.322] [ERROR] Error: Cannot find module 'request'

Missed unlisted dependency, solved with `npm install request`
